// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgmrfvuzsyindahwwoqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnbXJmdnV6c3lpbmRhaHd3b3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTE3NDUsImV4cCI6MjA2NTY4Nzc0NX0.kkiEOJE_e0nXsmIDIC2IzJMwxzpD6feu4-Y0YB8XyBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);